### ISSUE TITLE
newTask[AsyncTaskHandler] cannot be called

### ISSUE THREAD

**Issue by the-argus** [ire4ever1190/taskman#2]
The following expression worked fine:

```nim
    let task = taskman.newTask[taskman.TaskHandler](cronTiming, notification.notifyFunc())
```
Where notification.notifyFunc is a function which returns another function, and cronTiming is of type ``Cron``.
Upon switching to an AsyncScheduler, though, I needed to switch the handler to an ``AsyncTaskHandler``. Now I get the following error:

```
schedule.nim:34:57 Error: expression 'newTask[AsyncTaskHandler](cronTiming, notifyFunc(notification))' cannot be called
```

To reproduce, clone [my repository](https://github.com/the-argus/obsidian-tasks-ntfy), checkout commit ``1148d054c349308a07d5c6c9533bb52ce22ca2e0``, and run ``nimble build --threads=on``

**Comment by ire4ever1190** [comment]
Weird error message, it should've been a type mismatch.

Looking at your code you seem to be trying to pass a normal function when it needs an async function

Replacing `notifyFunc` in `src/notifications` with this fixed that error for me
```nim
proc notifyFunc*(notification: Notification): proc =
  return proc () {.async.} = notify(notification.message, notification.url)
```
Does that work for you?

Side note: I see you are using cron for it, wouldn't using the [datetime version](https://tempdocs.netlify.app/taskman/stable/taskman.html#newTask%2CDateTime%2CT) work better since you already have a date time in the notification?

P.S. Cool project, think I might see myself using it in the future

**Comment by the-argus** [comment]
Yes, everything is fixed, thanks so much. I'm developing a love/hate (but mostly hate) relationship with the nim compiler and its error messages.

Yes, in theory datetime would be better but the notifications can reoccur, so I thought just using cron for everything would be best. I know this a different question from the title but I'm going to leave this issue open because I'm wondering if it might be possible to manage recurrence with DateTime?

**Comment by ire4ever1190** [comment]
It would be possible I'm pretty sure

If the task handler has access to both the task and the scheduler then it could re add it

```nim

let tasks = newAsyncScheduler()

let date = now() + 5.seconds

proc handler () {.async.} =
  echo "task ran, see you again soon"
  tasks.at(date + 1.years, handler)
tasks.at(date, handler)

wait for tasks.start()
```

**Comment by ire4ever1190** [comment]
But yeah if basically doing that then Cron would probably make more sense

**Comment by the-argus** [comment]
okay, thanks so much.
